version: '3.8'
services:
  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - services
    volumes:
      - zookeeper-data:/bitnami

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ADVERTISED_PORT=9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - services
    volumes:
      - kafka-data:/bitnami

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=kafka:9092
    depends_on:
      - kafka
    networks:
      - services

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.8
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - PLUGIN_KAFKA_PRODUCER_CONFIG_ACKS=all
      - PLUGIN_KAFKA_PRODUCER_CONFIG_RETRIES=3
      - PLUGIN_EVENT_TYPE_CONFIG=LOGIN,LOGOUT,REGISTER,LOGIN_ERROR
      - PLUGIN_KAFKA_PRODUCER_CONFIG_BOOTSTRAP_SERVERS=kafka:9092
      - PLUGIN_KAFKA_TOPIC=kafka-keycloak-plugin
    ports:
      - "8383:8080"
    networks:
      - services
    command: >
      start-dev --verbose
    volumes:
      - keycloak-data:/opt/keycloak-data/data

networks:
  services:
    driver: bridge

volumes:
  zookeeper-data:
  kafka-data:
  keycloak-data: